version: '3.1'

services:
  device-microservice:
    hostname: device-microservice
    container_name: device-microservice
    build: .
    ports:
      - "8085:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sd_device
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwer1234
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=sd_device
    ports:
      - "3309:3306"